library:
  source-dirs: src
tests:
  haskell-tutorial-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tutorial
maintainer: a.demidenko@cactus.vision
dependencies:
- directory
- split
- base >= 4.7 && < 5
- time
- old-locale
name: haskell-tutorial
version: 0.1.0.0
extra-source-files:
- README.md
author: Andrey Demidenko
github: worm2fed/haskell-tutorial
license: Sonus
executables:
  haskell-tutorial-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tutorial
    - text
description: Please see the README on GitHub at <https://github.com/worm2fed/haskell-tutorial#readme>
